# Базовые понятия статистики

Задание 1. Базовое изучение
Изучить представленный набор данных на основе описания его столбцов и выбрать 8 столбцов для дальнейшего изучения (среди них должны быть как числовые, так и категориальные). Провести расчет базовых метрик для них, кратко описать результаты.

Задание 2. Работа с выбросами
В выбранных числовых столбцах найти выбросы, выдвинуть гипотезы об их причинах и проинтерпретировать результаты. Принять и обосновать решение о дальнейшей работе с ними.

Задание 3. Работа с пропусками
Рассчитать количество пропусков для всех выбранных столбцов. Принять и обосновать решение о методе работы с пропусками по каждому столбцу, сформировать датафрейм, в котором пропуски будут отсутствовать.

In [46]:
import pandas as pd
import numpy as np

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

pd.options.mode.chained_assignment = None  # default='warn'

df = pd.read_csv("horse_data.csv", 
            na_values='?',
            names = [
                "surgery", 
                "age", 
                "hospital_number", 
                "rectal_temperature", 
                "pulse",
                "respiratory_rate",
                "temperature_of_extremities", 
                "peripheral_pulse",
                "mucous_membranes",
                "capillary_refill_time",
                "pain",
                "peristalsis",
                "abdominal_distension",
                "nasogastric_tube",
                "nasogastric_reflux",
                "nasogastric_reflux_PH",
                "rectal_examination_feces",
                "abdomen",
                "packed_cell_volume",
                "total_protein",
                "abdominocentesis_appearance",
                "abdomcentesis_total_protein",
                "outcome",
                "surgical_lesion",
                "lesion_1",
                "lesion_2",
                "lesion_3",
                "cp_data",
            ])

df.head()

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2

In [47]:
# пропуски - %
for column in df.columns:
    res = df[column].isnull().mean()
    print(f'{column} - {res : 0.1%}')

surgery -  0.3%
age -  0.0%
hospital_number -  0.0%
rectal_temperature -  20.0%
pulse -  8.0%
respiratory_rate -  19.3%
temperature_of_extremities -  18.7%
peripheral_pulse -  23.0%
mucous_membranes -  15.7%
capillary_refill_time -  10.7%
pain -  18.3%
peristalsis -  14.7%
abdominal_distension -  18.7%
nasogastric_tube -  34.7%
nasogastric_reflux -  35.3%
nasogastric_reflux_PH -  82.3%
rectal_examination_feces -  34.0%
abdomen -  39.3%
packed_cell_volume -  9.7%
total_protein -  11.0%
abdominocentesis_appearance -  55.0%
abdomcentesis_total_protein -  66.0%
outcome -  0.3%
surgical_lesion -  0.0%
lesion_1 -  0.0%
lesion_2 -  0.0%
lesion_3 -  0.0%
cp_data -  0.0%

In [48]:
#базовые метрики для количественных значений
df[['rectal_temperature', 'pulse', 'respiratory_rate']].describe()

       rectal_temperature       pulse  respiratory_rate
count          240.000000  276.000000        242.000000
mean            38.167917   71.913043         30.417355
std              0.732289   28.630557         17.642231
min             35.400000   30.000000          8.000000
25%             37.800000   48.000000         18.500000
50%             38.200000   64.000000         24.500000
75%             38.500000   88.000000         36.000000
max             40.800000  184.000000         96.000000

In [49]:
#Посмотрим выбросы по ключу rectal_temperature

quantile1 = df.rectal_temperature.quantile(0.25)
quantile3 = df.rectal_temperature.quantile(0.75)
iqr = quantile3 - quantile1
lower = quantile1 - (1.5 * iqr) 
upper = quantile3 + (1.5 * iqr)

df[(df.rectal_temperature < lower) | (df.rectal_temperature > upper)].sort_values('rectal_temperature')

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
44,1.0,1,535407,35.4,140.0,24.0,3.0,3.0,4.0,2.0,...,57.0,69.0,3.0,2.0,3.0,1,3205,0,0,2
141,2.0,1,522979,36.0,42.0,30.0,NaN,NaN,5.0,1.0,...,64.0,6.8,NaN,NaN,2.0,2,1400,0,0,2
238,2.0,1,528702,36.1,88.0,NaN,3.0,3.0,3.0,1.0,...,45.0,7.0,3.0,4.8,3.0,1,2209,0,0,1
80,1.0,1,527518,36.4,98.0,35.0,3.0,3.0,4.0,1.0,...,47.0,6.4,3.0,3.6,2.0,1,2205,0,0,1
118,1.0,1,533983,36.5,78.0,30.0,1.0,NaN,1.0,1.0,...,34.0,75.0,2.0,1.0,1.0,1,3112,6112,0,2
298,1.0,1,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.0,3.0,3.4,1.0,1,2208,0,0,1
251,2.0,1,527940,36.6,42.0,18.0,3.0,3.0,2.0,1.0,...,52.0,7.1,NaN,NaN,2.0,1,5111,0,0,2
99,2.0,1,530002,39.6,108.0,51.0,3.0,3.0,6.0,2.0,...,59.0,8.0,2.0,2.6,1.0,2,4300,0,0,1
75,1.0,9,534092,39.7,100.0,NaN,3.0,3.0,5.0,2.0,...,48.0,57.0,2.0,2.0,3.0,1,1400,0,0,2
20,1.0,1,530157,39.9,72.0,60.0,1.0,1.0,5.0,2.0,...,46.0,6.1,2.0,NaN,1.0,1,2111,0,0,2
281,2.0,1,530624,40.0,78.0,NaN,3.0,3.0,5.0,1.0,...,66.0,6.5,NaN,NaN,2.0,1,8400,0,0,1
54,2.0,1,529461,40.3,114.0,36.0,3.0,3.0,1.0,2.0,...,57.0,8.1,3.0,4.5,3.0,1,7400,0,0,1
91,2.0,1,529461,40.3,114.0,36.0,3.0,3.0,1.0,2.0,...,57.0,8.1,3.0,4.5,2.0,1,3205,0,0,1
259,1.0,1,527734,40.8,72.0,42.0,3.0,3.0,1.0,1.0,...,54.0,7.4,3.0,NaN,2.0,1,11400,0,0,1

In [50]:
#Посмотрим выбросы по ключу pulse

quantile1 = df.pulse.quantile(0.25)
quantile3 = df.pulse.quantile(0.75)
iqr = quantile3 - quantile1
lower = quantile1 - (1.5 * iqr) 
upper = quantile3 + (1.5 * iqr)

df[df.pulse.between(lower, upper, inclusive=True)]

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
6,1.0,1,526802,37.9,48.0,16.0,1.0,1.0,1.0,1.0,...,37.0,7.0,NaN,NaN,1.0,1,3124,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,NaN,120.0,70.0,4.0,NaN,4.0,2.0,...,55.0,65.0,NaN,NaN,3.0,2,3205,0,0,2
296,2.0,1,527702,37.2,72.0,24.0,3.0,2.0,4.0,2.0,...,44.0,NaN,3.0,3.3,3.0,1,2208,0,0,1
297,1.0,1,529386,37.5,72.0,30.0,4.0,3.0,4.0,1.0,...,60.0,6.8,NaN,NaN,2.0,1,3205,0,0,2
298,1.0,1,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.0,3.0,3.4,1.0,1,2208,0,0,1
299,1.0,1,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,1.0,1.0,3.0,2,6112,0,0,2

In [51]:
#surgery?
#1 = Yes, it had surgery
#2 = It was treated without surgery

In [52]:
# заменим на категорийное значение
df.loc[df['surgery'] == 1, 'surgery'] = 'yes'
df.loc[df['surgery'] == 2, 'surgery'] = 'no'


df[df['surgery'].isna()]

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
132,NaN,1,534572,38.0,48.0,20.0,3.0,1.0,3.0,1.0,...,43.0,73.0,2.0,1.0,NaN,1,3111,0,0,2

In [53]:
# судя по lesion_1 операция была, проставим пропущенное значение
df['surgery'].iloc[132] = 'yes'

df.head()

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,yes,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,no,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,yes,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,no,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2

In [54]:
#Age
#1 = Adult horse
#2 = Young( < 6 months)

#Вероятно, число 9 было указано вместо 2, при замене на категорийное значение учтем это
df.loc[df['age'] == 1, 'age'] = 'adult'
df.loc[df['age'] == 9, 'age'] = 'young'

df.head()

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,yes,adult,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,no,adult,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,yes,young,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,no,adult,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2

In [55]:
#пропуски отсутствуют
df[df['age'].isna()]

Empty DataFrame
Columns: [surgery, age, hospital_number, rectal_temperature, pulse, respiratory_rate, temperature_of_extremities, peripheral_pulse, mucous_membranes, capillary_refill_time, pain, peristalsis, abdominal_distension, nasogastric_tube, nasogastric_reflux, nasogastric_reflux_PH, rectal_examination_feces, abdomen, packed_cell_volume, total_protein, abdominocentesis_appearance, abdomcentesis_total_protein, outcome, surgical_lesion, lesion_1, lesion_2, lesion_3, cp_data]
Index: []

[0 rows x 28 columns]

In [56]:
#hospital_number
# - numeric id
# - the case number assigned to the horse(may not be unique if the horse is treated > 1 time)

#категориальная величина, номер дела в госпитале
#пропуски отсутствуют
df[df['hospital_number'].isna()]

Empty DataFrame
Columns: [surgery, age, hospital_number, rectal_temperature, pulse, respiratory_rate, temperature_of_extremities, peripheral_pulse, mucous_membranes, capillary_refill_time, pain, peristalsis, abdominal_distension, nasogastric_tube, nasogastric_reflux, nasogastric_reflux_PH, rectal_examination_feces, abdomen, packed_cell_volume, total_protein, abdominocentesis_appearance, abdomcentesis_total_protein, outcome, surgical_lesion, lesion_1, lesion_2, lesion_3, cp_data]
Index: []

[0 rows x 28 columns]

In [57]:
#rectal_temperature
# - linear
# - in degrees celsius.
# - An elevated temp may occur due to infection.
# - temperature may be reduced when the animal is in late shock
# - normal temp is 37.8
# - this parameter will usually change as the problem progresses eg.may start out normal, then become elevated because of the lesion, passing back through the normal range as the horse goes into shock

# процент пропусков
print(round(len(df.loc[df['rectal_temperature'].isna()]) / len(df.index) * 100, 1), "%")

20.0 %

In [58]:
#неприрывная величина, температура тела лошади
df[df['rectal_temperature'].isna()]

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
5,no,adult,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
7,yes,adult,529607,NaN,60.0,NaN,3.0,NaN,NaN,1.0,...,44.0,8.3,NaN,NaN,2.0,1,2208,0,0,2
8,no,adult,530051,NaN,80.0,36.0,3.0,4.0,3.0,1.0,...,38.0,6.2,NaN,NaN,3.0,1,3205,0,0,2
16,yes,young,5301219,NaN,128.0,36.0,3.0,3.0,4.0,2.0,...,53.0,7.8,3.0,4.7,2.0,2,1400,0,0,1
28,yes,adult,5279442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,2,4300,0,0,2
34,yes,adult,529796,NaN,100.0,30.0,3.0,3.0,4.0,2.0,...,52.0,6.6,NaN,NaN,1.0,1,1124,0,0,2
35,no,adult,528812,NaN,104.0,24.0,4.0,3.0,3.0,2.0,...,73.0,8.4,NaN,NaN,3.0,1,7111,0,0,2
40,yes,adult,529498,NaN,88.0,NaN,3.0,3.0,6.0,2.0,...,63.0,6.5,3.0,NaN,2.0,1,4205,0,0,2
43,yes,adult,534069,NaN,120.0,NaN,3.0,4.0,4.0,1.0,...,52.0,67.0,2.0,2.0,3.0,1,3205,0,0,2
45,no,adult,529827,NaN,120.0,NaN,4.0,3.0,4.0,2.0,...,60.0,6.5,3.0,NaN,2.0,1,3205,0,0,2
52,no,adult,529483,NaN,NaN,NaN,1.0,1.0,3.0,1.0,...,43.0,7.7,NaN,NaN,1.0,2,3111,0,0,2
56,yes,adult,528872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.0,6.7,NaN,NaN,1.0,1,3112,0,0,2
57,yes,adult,529640,NaN,64.0,36.0,2.0,NaN,2.0,1.0,...,42.0,7.7,NaN,NaN,2.0,1,3209,0,0,2
58,yes,adult,528298,NaN,NaN,20.0,4.0,3.0,3.0,NaN,...,53.0,5.9,3.0,NaN,2.0,1,3205,0,0,1
59,no,adult,528904,NaN,96.0,NaN,3.0,3.0,3.0,2.0,...,60.0,NaN,NaN,NaN,2.0,1,4205,0,0,2
65,yes,adult,534885,NaN,60.0,36.0,3.0,1.0,3.0,1.0,...,26.0,72.0,2.0,1.0,1.0,1,2208,0,0,2
68,no,adult,529777,NaN,52.0,16.0,1.0,NaN,3.0,1.0,...,55.0,7.2,NaN,NaN,1.0,2,2124,0,0,2
74,yes,young,5292929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.0,4.9,NaN,NaN,2.0,1,11124,0,0,2
78,yes,adult,530693,NaN,NaN,NaN,3.0,3.0,3.0,3.0,...,46.0,5.9,NaN,NaN,2.0,1,3025,0,0,2
86,yes,adult,529388,NaN,88.0,40.0,3.0,3.0,4.0,2.0,...,50.0,7.7,3.0,1.4,2.0,1,4205,0,0,1
87,no,adult,528006,NaN,40.0,16.0,NaN,NaN,NaN,1.0,...,50.0,7.0,2.0,3.9,3.0,1,2208,0,0,1
93,no,adult,530310,NaN,NaN,NaN,3.0,3.0,1.0,1.0,...,38.0,6.5,NaN,NaN,2.0,1,3205,0,0,2
96,no,adult,530319,NaN,84.0,36.0,NaN,NaN,3.0,1.0,...,44.0,8.5,NaN,NaN,1.0,1,3111,0,0,2
101,yes,adult,534899,NaN,60.0,20.0,4.0,3.0,4.0,2.0,...,NaN,NaN,NaN,NaN,3.0,1,3205,0,0,2
105,yes,adult,530381,NaN,70.0,36.0,1.0,NaN,3.0,2.0,...,36.0,7.3,NaN,NaN,1.0,1,31110,0,0,2
110,yes,adult,527544,NaN,70.0,16.0,3.0,4.0,5.0,2.0,...,60.0,7.5,NaN,NaN,2.0,1,2112,0,0,2
112,yes,adult,534963,NaN,40.0,NaN,2.0,1.0,1.0,1.0,...,39.0,56.0,NaN,NaN,1.0,1,3111,0,0,2
115,no,adult,533723,NaN,NaN,40.0,3.0,1.0,1.0,1.0,...,45.0,70.0,NaN,NaN,1.0,2,0,0,0,2
134,yes,adult,527524,NaN,100.0,NaN,3.0,NaN,4.0,2.0,...,59.0,6.3,NaN,NaN,2.0,1,4205,0,0,2
136,yes,adult,530693,NaN,NaN,NaN,3.0,3.0,3.0,2.0,...,46.0,5.9,NaN,NaN,2.0,1,3025,0,0,2
142,yes,adult,530402,NaN,120.0,NaN,4.0,3.0,6.0,2.0,...,57.0,4.5,3.0,3.9,2.0,1,3205,0,0,1
145,no,adult,535246,NaN,80.0,32.0,3.0,3.0,2.0,1.0,...,50.0,80.0,NaN,NaN,1.0,1,0,0,0,2
152,yes,adult,533836,NaN,100.0,NaN,3.0,3.0,4.0,2.0,...,68.0,64.0,3.0,2.0,1.0,1,2209,0,0,2
159,no,adult,528134,NaN,NaN,12.0,1.0,1.0,2.0,1.0,...,44.0,7.5,2.0,NaN,1.0,2,0,0,0,1
160,yes,adult,527916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.0,58.0,2.0,1.0,1.0,1,4205,0,0,2
167,no,adult,528299,NaN,44.0,24.0,1.0,1.0,1.0,1.0,...,NaN,6.3,NaN,NaN,1.0,2,3111,0,0,2
169,yes,adult,535085,NaN,65.0,24.0,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,3.0,1,3205,0,0,2
173,yes,adult,529729,NaN,104.0,NaN,3.0,3.0,5.0,2.0,...,69.0,8.6,2.0,3.4,2.0,1,2207,0,0,1
174,no,adult,518476,NaN,NaN,NaN,3.0,4.0,6.0,NaN,...,NaN,NaN,NaN,NaN,2.0,1,3400,0,0,1
175,yes,adult,527929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2208,0,0,2
177,yes,adult,523190,NaN,68.0,14.0,NaN,NaN,4.0,1.0,...,NaN,NaN,2.0,2.8,2.0,1,4205,0,0,1
178,yes,adult,533968,NaN,60.0,30.0,3.0,3.0,4.0,2.0,...,45.0,70.0,3.0,2.0,1.0,1,6111,3111,0,2
191,no,young,5287279,NaN,100.0,44.0,2.0,1.0,1.0,1.0,...,37.0,4.7,NaN,NaN,1.0,2,7111,0,0,2
193,yes,adult,529373,NaN,60.0,48.0,3.0,3.0,4.0,2.0,...,58.0,7.6,NaN,NaN,2.0,1,3205,0,0,2
207,yes,adult,530297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,8.7,NaN,NaN,2.0,1,2208,0,0,2
216,no,adult,528977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
219,yes,adult,529736,NaN,52.0,28.0,3.0,3.0,4.0,1.0,...,37.0,8.1,NaN,NaN,1.0,1,2111,0,0,2
222,yes,adult,528800,NaN,112.0,13.0,4.0,4.0,4.0,1.0,...,60.0,6.3,3.0,NaN,1.0,1,2205,0,0,1
227,yes,young,5289419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,6.5,2.0,NaN,1.0,1,9000,0,0,1
242,yes,adult,530354,NaN,36.0,32.0,1.0,1.0,4.0,1.0,...,41.0,5.9,NaN,NaN,2.0,1,2205,0,0,2
245,no,adult,528904,NaN,96.0,NaN,3.0,3.0,3.0,2.0,...,60.0,NaN,NaN,NaN,2.0,1,41110,0,0,2
253,no,adult,530561,NaN,112.0,24.0,3.0,3.0,4.0,2.0,...,40.0,5.3,3.0,2.6,1.0,2,400,0,0,1
254,yes,adult,533738,NaN,80.0,NaN,3.0,3.0,3.0,1.0,...,43.0,70.0,NaN,NaN,1.0,1,3111,0,0,2
265,no,adult,528590,NaN,56.0,68.0,3.0,1.0,1.0,1.0,...,40.0,6.0,NaN,NaN,3.0,1,5206,0,0,2
272,yes,adult,529796,NaN,100.0,30.0,3.0,3.0,4.0,2.0,...,52.0,6.6,NaN,NaN,1.0,1,2124,0,0,2
274,yes,adult,534624,NaN,76.0,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,1,11124,0,0,2
282,yes,adult,527544,NaN,70.0,16.0,3.0,4.0,5.0,2.0,...,60.0,7.5,NaN,NaN,2.0,1,1400,0,0,2
288,yes,adult,529428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2124,0,0,2
293,yes,adult,534004,NaN,78.0,24.0,3.0,3.0,3.0,1.0,...,43.0,62.0,NaN,2.0,3.0,2,2209,0,0,2
295,yes,adult,533886,NaN,120.0,70.0,4.0,NaN,4.0,2.0,...,55.0,65.0,NaN,NaN,3.0,2,3205,0,0,2

In [59]:
#пропуски заполним медианой
df['rectal_temperature'].fillna(df.groupby(['age', 'surgery'])['rectal_temperature'].transform('median'), inplace = True)
df.head(20)

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,yes,adult,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,no,adult,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,yes,young,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,no,adult,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
5,no,adult,528355,38.2,NaN,NaN,2.0,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
6,yes,adult,526802,37.9,48.0,16.0,1.0,1.0,1.0,1.0,...,37.0,7.0,NaN,NaN,1.0,1,3124,0,0,2
7,yes,adult,529607,38.1,60.0,NaN,3.0,NaN,NaN,1.0,...,44.0,8.3,NaN,NaN,2.0,1,2208,0,0,2
8,no,adult,530051,38.2,80.0,36.0,3.0,4.0,3.0,1.0,...,38.0,6.2,NaN,NaN,3.0,1,3205,0,0,2
9,no,young,5299629,38.3,90.0,NaN,1.0,NaN,1.0,1.0,...,40.0,6.2,1.0,2.2,1.0,2,0,0,0,1
10,yes,adult,528548,38.1,66.0,12.0,3.0,3.0,5.0,1.0,...,44.0,6.0,2.0,3.6,1.0,1,2124,0,0,1
11,no,adult,527927,39.1,72.0,52.0,2.0,NaN,2.0,1.0,...,50.0,7.8,NaN,NaN,1.0,1,2111,0,0,2
12,yes,adult,528031,37.2,42.0,12.0,2.0,1.0,1.0,1.0,...,NaN,7.0,NaN,NaN,1.0,2,4124,0,0,2
13,no,young,5291329,38.0,92.0,28.0,1.0,1.0,2.0,1.0,...,37.0,6.1,1.0,NaN,2.0,2,0,0,0,1
14,yes,adult,534917,38.2,76.0,28.0,3.0,1.0,1.0,1.0,...,46.0,81.0,1.0,2.0,1.0,1,2112,0,0,2
15,yes,adult,530233,37.6,96.0,48.0,3.0,1.0,4.0,1.0,...,45.0,6.8,NaN,NaN,2.0,1,3207,0,0,2
16,yes,young,5301219,38.6,128.0,36.0,3.0,3.0,4.0,2.0,...,53.0,7.8,3.0,4.7,2.0,2,1400,0,0,1
17,no,adult,526639,37.5,48.0,24.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
18,yes,adult,5290481,37.6,64.0,21.0,1.0,1.0,2.0,1.0,...,40.0,7.0,1.0,NaN,1.0,1,4205,0,0,1
19,no,adult,532110,39.4,110.0,35.0,4.0,3.0,6.0,NaN,...,55.0,8.7,NaN,NaN,1.0,2,0,0,0,2

In [60]:
#Посмотрим выбросы
quantile1 = df.rectal_temperature.quantile(0.25)
quantile3 = df.rectal_temperature.quantile(0.75)
iqr = quantile3 - quantile1
lower = quantile1 - (1.5 * iqr) 
upper = quantile3 + (1.5 * iqr)

df[(df.rectal_temperature < lower) | (df.rectal_temperature > upper)].sort_values('rectal_temperature')

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
44,yes,adult,535407,35.4,140.0,24.0,3.0,3.0,4.0,2.0,...,57.0,69.0,3.0,2.0,3.0,1,3205,0,0,2
141,no,adult,522979,36.0,42.0,30.0,NaN,NaN,5.0,1.0,...,64.0,6.8,NaN,NaN,2.0,2,1400,0,0,2
238,no,adult,528702,36.1,88.0,NaN,3.0,3.0,3.0,1.0,...,45.0,7.0,3.0,4.8,3.0,1,2209,0,0,1
80,yes,adult,527518,36.4,98.0,35.0,3.0,3.0,4.0,1.0,...,47.0,6.4,3.0,3.6,2.0,1,2205,0,0,1
118,yes,adult,533983,36.5,78.0,30.0,1.0,NaN,1.0,1.0,...,34.0,75.0,2.0,1.0,1.0,1,3112,6112,0,2
298,yes,adult,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.0,3.0,3.4,1.0,1,2208,0,0,1
251,no,adult,527940,36.6,42.0,18.0,3.0,3.0,2.0,1.0,...,52.0,7.1,NaN,NaN,2.0,1,5111,0,0,2
113,yes,adult,527933,36.8,60.0,28.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.0,2.0,1,3205,0,0,1
277,no,adult,528620,36.9,50.0,40.0,2.0,3.0,3.0,1.0,...,37.5,6.5,NaN,NaN,1.0,2,3111,0,0,2
117,no,adult,5290482,39.5,NaN,NaN,3.0,3.0,4.0,2.0,...,NaN,6.7,1.0,NaN,3.0,1,4205,0,0,2
287,no,young,5305129,39.5,84.0,30.0,NaN,NaN,NaN,1.0,...,28.0,5.0,NaN,NaN,1.0,2,0,0,0,2
162,no,adult,535176,39.5,60.0,10.0,3.0,NaN,NaN,2.0,...,38.0,56.0,1.0,NaN,1.0,2,0,0,0,2
231,no,adult,530028,39.5,92.0,28.0,3.0,3.0,6.0,1.0,...,72.0,6.4,NaN,3.6,2.0,2,3300,0,0,2
99,no,adult,530002,39.6,108.0,51.0,3.0,3.0,6.0,2.0,...,59.0,8.0,2.0,2.6,1.0,2,4300,0,0,1
75,yes,young,534092,39.7,100.0,NaN,3.0,3.0,5.0,2.0,...,48.0,57.0,2.0,2.0,3.0,1,1400,0,0,2
20,yes,adult,530157,39.9,72.0,60.0,1.0,1.0,5.0,2.0,...,46.0,6.1,2.0,NaN,1.0,1,2111,0,0,2
281,no,adult,530624,40.0,78.0,NaN,3.0,3.0,5.0,1.0,...,66.0,6.5,NaN,NaN,2.0,1,8400,0,0,1
54,no,adult,529461,40.3,114.0,36.0,3.0,3.0,1.0,2.0,...,57.0,8.1,3.0,4.5,3.0,1,7400,0,0,1
91,no,adult,529461,40.3,114.0,36.0,3.0,3.0,1.0,2.0,...,57.0,8.1,3.0,4.5,2.0,1,3205,0,0,1
259,yes,adult,527734,40.8,72.0,42.0,3.0,3.0,1.0,1.0,...,54.0,7.4,3.0,NaN,2.0,1,11400,0,0,1

In [61]:
#pulse
# - linear
# - the heart rate in beats per minute
# - is a reflection of the heart condition: 30 - 40 is normal for adults
# - rare to have a lower than normal rate although athletic horses may have a rate of 20 - 25
# - animals with painful lesions or suffering from circulatory shock may have an elevated heart rate

#неприрывная величина, значение пульса лошади

# процент пропусков
print(round(len(df.loc[df['pulse'].isna()]) / len(df.index) * 100, 1), "%")

8.0 %

In [62]:
df.loc[df['pulse'].isna()]

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
5,no,adult,528355,38.2,NaN,NaN,2.0,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
28,yes,adult,5279442,38.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,2,4300,0,0,2
52,no,adult,529483,38.2,NaN,NaN,1.0,1.0,3.0,1.0,...,43.0,7.7,NaN,NaN,1.0,2,3111,0,0,2
56,yes,adult,528872,38.1,NaN,NaN,NaN,NaN,NaN,NaN,...,24.0,6.7,NaN,NaN,1.0,1,3112,0,0,2
58,yes,adult,528298,38.1,NaN,20.0,4.0,3.0,3.0,NaN,...,53.0,5.9,3.0,NaN,2.0,1,3205,0,0,1
74,yes,young,5292929,38.6,NaN,NaN,NaN,NaN,NaN,NaN,...,37.0,4.9,NaN,NaN,2.0,1,11124,0,0,2
78,yes,adult,530693,38.1,NaN,NaN,3.0,3.0,3.0,3.0,...,46.0,5.9,NaN,NaN,2.0,1,3025,0,0,2
83,yes,adult,5279822,38.0,NaN,24.0,3.0,3.0,6.0,2.0,...,68.0,7.8,NaN,NaN,2.0,1,3205,0,0,2
93,no,adult,530310,38.2,NaN,NaN,3.0,3.0,1.0,1.0,...,38.0,6.5,NaN,NaN,2.0,1,3205,0,0,2
115,no,adult,533723,38.2,NaN,40.0,3.0,1.0,1.0,1.0,...,45.0,70.0,NaN,NaN,1.0,2,0,0,0,2
117,no,adult,5290482,39.5,NaN,NaN,3.0,3.0,4.0,2.0,...,NaN,6.7,1.0,NaN,3.0,1,4205,0,0,2
126,yes,adult,530384,38.7,NaN,NaN,3.0,1.0,3.0,1.0,...,33.0,6.5,2.0,NaN,1.0,1,31110,0,0,2
136,yes,adult,530693,38.1,NaN,NaN,3.0,3.0,3.0,2.0,...,46.0,5.9,NaN,NaN,2.0,1,3025,0,0,2
151,yes,adult,529399,39.3,NaN,NaN,4.0,3.0,6.0,2.0,...,75.0,NaN,3.0,4.3,2.0,1,2207,0,0,1
159,no,adult,528134,38.2,NaN,12.0,1.0,1.0,2.0,1.0,...,44.0,7.5,2.0,NaN,1.0,2,0,0,0,1
160,yes,adult,527916,38.1,NaN,NaN,NaN,NaN,NaN,NaN,...,35.0,58.0,2.0,1.0,1.0,1,4205,0,0,2
174,no,adult,518476,38.2,NaN,NaN,3.0,4.0,6.0,NaN,...,NaN,NaN,NaN,NaN,2.0,1,3400,0,0,1
175,yes,adult,527929,38.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2208,0,0,2
182,yes,adult,5279822,38.0,NaN,24.0,3.0,3.0,6.0,2.0,...,68.0,7.8,NaN,NaN,2.0,1,2205,0,0,2
204,yes,adult,529528,39.2,NaN,23.0,3.0,1.0,3.0,1.0,...,36.0,6.6,1.0,3.0,1.0,1,3115,0,0,1
207,yes,adult,530297,38.1,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,8.7,NaN,NaN,2.0,1,2208,0,0,2
216,no,adult,528977,38.2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
227,yes,young,5289419,38.6,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,6.5,2.0,NaN,1.0,1,9000,0,0,1
288,yes,adult,529428,38.1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2124,0,0,2

In [63]:
df['pulse'].fillna(df.groupby(['age', 'surgery'])['pulse'].transform('median'), inplace = True)
df['pulse']

0       66.0
1       88.0
2       40.0
3      164.0
4      104.0
       ...
295    120.0
296     72.0
297     72.0
298    100.0
299     40.0
Name: pulse, Length: 300, dtype: float64

In [64]:
#respiratory_rate
# - linear
# - normal rate is 8 to 10
# - usefulness is doubtful due to the great fluctuations

#неприрывная величина, частота дыхания лошади
df.loc[df['respiratory_rate'].isna()]

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
5,no,adult,528355,38.2,54.0,NaN,2.0,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
7,yes,adult,529607,38.1,60.0,NaN,3.0,NaN,NaN,1.0,...,44.0,8.3,NaN,NaN,2.0,1,2208,0,0,2
9,no,young,5299629,38.3,90.0,NaN,1.0,NaN,1.0,1.0,...,40.0,6.2,1.0,2.2,1.0,2,0,0,0,1
28,yes,adult,5279442,38.1,66.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,2,4300,0,0,2
29,no,adult,535415,37.7,48.0,NaN,2.0,1.0,1.0,1.0,...,45.0,76.0,NaN,NaN,1.0,2,0,0,0,2
32,yes,adult,529427,37.2,60.0,NaN,2.0,1.0,1.0,1.0,...,43.0,6.6,NaN,NaN,1.0,1,2209,0,0,2
37,yes,adult,533847,37.8,72.0,NaN,NaN,3.0,NaN,1.0,...,56.0,80.0,1.0,2.0,1.0,1,3111,0,0,2
38,no,adult,528996,38.6,52.0,NaN,1.0,1.0,1.0,1.0,...,32.0,6.6,1.0,5.0,1.0,2,0,0,0,1
40,yes,adult,529498,38.1,88.0,NaN,3.0,3.0,6.0,2.0,...,63.0,6.5,3.0,NaN,2.0,1,4205,0,0,2
43,yes,adult,534069,38.1,120.0,NaN,3.0,4.0,4.0,1.0,...,52.0,67.0,2.0,2.0,3.0,1,3205,0,0,2
45,no,adult,529827,38.2,120.0,NaN,4.0,3.0,4.0,2.0,...,60.0,6.5,3.0,NaN,2.0,1,3205,0,0,2
50,no,adult,529766,38.6,46.0,NaN,1.0,1.0,2.0,1.0,...,49.0,9.1,1.0,1.6,1.0,2,3111,0,0,1
52,no,adult,529483,38.2,54.0,NaN,1.0,1.0,3.0,1.0,...,43.0,7.7,NaN,NaN,1.0,2,3111,0,0,2
56,yes,adult,528872,38.1,66.0,NaN,NaN,NaN,NaN,NaN,...,24.0,6.7,NaN,NaN,1.0,1,3112,0,0,2
59,no,adult,528904,38.2,96.0,NaN,3.0,3.0,3.0,2.0,...,60.0,NaN,NaN,NaN,2.0,1,4205,0,0,2
61,no,adult,527957,38.5,60.0,NaN,2.0,2.0,1.0,1.0,...,44.0,7.7,NaN,NaN,1.0,2,0,0,0,2
66,no,adult,534784,37.9,72.0,NaN,1.0,1.0,5.0,2.0,...,58.0,74.0,1.0,2.0,1.0,1,2322,0,0,2
72,yes,adult,5299253,37.7,56.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
74,yes,young,5292929,38.6,129.0,NaN,NaN,NaN,NaN,NaN,...,37.0,4.9,NaN,NaN,2.0,1,11124,0,0,2
75,yes,young,534092,39.7,100.0,NaN,3.0,3.0,5.0,2.0,...,48.0,57.0,2.0,2.0,3.0,1,1400,0,0,2
78,yes,adult,530693,38.1,66.0,NaN,3.0,3.0,3.0,3.0,...,46.0,5.9,NaN,NaN,2.0,1,3025,0,0,2
81,yes,adult,534756,37.3,40.0,NaN,NaN,3.0,1.0,1.0,...,36.0,NaN,3.0,2.0,1.0,1,3111,0,0,2
93,no,adult,530310,38.2,54.0,NaN,3.0,3.0,1.0,1.0,...,38.0,6.5,NaN,NaN,2.0,1,3205,0,0,2
112,yes,adult,534963,38.1,40.0,NaN,2.0,1.0,1.0,1.0,...,39.0,56.0,NaN,NaN,1.0,1,3111,0,0,2
117,no,adult,5290482,39.5,54.0,NaN,3.0,3.0,4.0,2.0,...,NaN,6.7,1.0,NaN,3.0,1,4205,0,0,2
126,yes,adult,530384,38.7,66.0,NaN,3.0,1.0,3.0,1.0,...,33.0,6.5,2.0,NaN,1.0,1,31110,0,0,2
129,yes,adult,527698,38.4,49.0,NaN,NaN,NaN,1.0,1.0,...,44.0,7.6,NaN,NaN,1.0,1,2206,0,0,2
134,yes,adult,527524,38.1,100.0,NaN,3.0,NaN,4.0,2.0,...,59.0,6.3,NaN,NaN,2.0,1,4205,0,0,2
136,yes,adult,530693,38.1,66.0,NaN,3.0,3.0,3.0,2.0,...,46.0,5.9,NaN,NaN,2.0,1,3025,0,0,2
137,yes,adult,534324,38.0,48.0,NaN,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,1.0,1,3111,0,0,2
138,no,adult,532349,38.0,56.0,NaN,1.0,2.0,3.0,1.0,...,42.0,71.0,NaN,NaN,1.0,2,0,0,0,2
142,yes,adult,530402,38.1,120.0,NaN,4.0,3.0,6.0,2.0,...,57.0,4.5,3.0,3.9,2.0,1,3205,0,0,1
146,yes,adult,534115,38.2,48.0,NaN,1.0,3.0,3.0,1.0,...,42.0,71.0,NaN,NaN,1.0,1,3111,0,0,2
148,yes,adult,529272,38.3,132.0,NaN,NaN,3.0,6.0,2.0,...,57.0,8.0,NaN,5.2,1.0,1,2112,0,0,1
151,yes,adult,529399,39.3,66.0,NaN,4.0,3.0,6.0,2.0,...,75.0,NaN,3.0,4.3,2.0,1,2207,0,0,1
152,yes,adult,533836,38.1,100.0,NaN,3.0,3.0,4.0,2.0,...,68.0,64.0,3.0,2.0,1.0,1,2209,0,0,2
160,yes,adult,527916,38.1,66.0,NaN,NaN,NaN,NaN,NaN,...,35.0,58.0,2.0,1.0,1.0,1,4205,0,0,2
164,yes,adult,528523,38.7,76.0,NaN,1.0,1.0,5.0,2.0,...,50.0,8.0,NaN,NaN,1.0,1,2208,0,0,1
173,yes,adult,529729,38.1,104.0,NaN,3.0,3.0,5.0,2.0,...,69.0,8.6,2.0,3.4,2.0,1,2207,0,0,1
174,no,adult,518476,38.2,54.0,NaN,3.0,4.0,6.0,NaN,...,NaN,NaN,NaN,NaN,2.0,1,3400,0,0,1
175,yes,adult,527929,38.1,66.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2208,0,0,2
179,no,adult,528151,38.5,100.0,NaN,3.0,3.0,5.0,2.0,...,NaN,NaN,NaN,NaN,3.0,2,1111,0,0,1
188,yes,adult,533887,38.5,60.0,NaN,1.0,1.0,NaN,1.0,...,33.0,53.0,1.0,NaN,1.0,1,4111,0,0,2
201,yes,adult,528641,38.5,86.0,NaN,1.0,1.0,3.0,1.0,...,45.0,7.4,1.0,3.4,2.0,1,3209,0,0,1
205,no,adult,528151,38.5,100.0,NaN,3.0,3.0,5.0,2.0,...,NaN,NaN,NaN,NaN,3.0,2,4124,0,0,2
207,yes,adult,530297,38.1,66.0,NaN,NaN,NaN,NaN,NaN,...,45.0,8.7,NaN,NaN,2.0,1,2208,0,0,2
216,no,adult,528977,38.2,54.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
227,yes,young,5289419,38.6,129.0,NaN,NaN,NaN,NaN,NaN,...,45.0,6.5,2.0,NaN,1.0,1,9000,0,0,1
238,no,adult,528702,36.1,88.0,NaN,3.0,3.0,3.0,1.0,...,45.0,7.0,3.0,4.8,3.0,1,2209,0,0,1
245,no,adult,528904,38.2,96.0,NaN,3.0,3.0,3.0,2.0,...,60.0,NaN,NaN,NaN,2.0,1,41110,0,0,2
249,no,adult,528169,38.2,48.0,NaN,2.0,NaN,1.0,2.0,...,34.0,6.6,NaN,NaN,1.0,2,3111,0,0,2
254,yes,adult,533738,38.1,80.0,NaN,3.0,3.0,3.0,1.0,...,43.0,70.0,NaN,NaN,1.0,1,3111,0,0,2
256,yes,adult,533871,37.5,72.0,NaN,2.0,1.0,1.0,1.0,...,35.0,65.0,2.0,2.0,3.0,1,7209,0,0,2
271,yes,adult,534626,37.7,80.0,NaN,3.0,3.0,6.0,1.0,...,50.0,55.0,3.0,2.0,1.0,1,4206,0,0,2
274,yes,adult,534624,38.1,76.0,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,1,11124,0,0,2
281,no,adult,530624,40.0,78.0,NaN,3.0,3.0,5.0,1.0,...,66.0,6.5,NaN,NaN,2.0,1,8400,0,0,1
284,no,adult,530439,38.5,54.0,NaN,1.0,1.0,1.0,1.0,...,40.0,6.8,2.0,7.0,1.0,2,0,0,0,1
288,yes,adult,529428,38.1,66.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2124,0,0,2

In [65]:
# процент пропусков
print(round(len(df.loc[df['respiratory_rate'].isna()]) / len(df.index) * 100, 1), "%")

19.3 %

In [66]:
df['respiratory_rate'].fillna(df.groupby(['age', 'surgery'])['respiratory_rate'].transform('median'), inplace = True)
df['respiratory_rate']

0      28.0
1      20.0
2      24.0
3      84.0
4      35.0
       ...
295    70.0
296    24.0
297    30.0
298    24.0
299    20.0
Name: respiratory_rate, Length: 300, dtype: float64

In [67]:
#temperature_of_extremities
# - a subjective indication of peripheral circulation
# - possible values:
#   1 = Normal 
#   2 = Warm 
#   3 = Cool 
#   4 = Cold

#cool to cold extremities indicate possible shock
#hot extremities should correlate with an elevated rectal temp.


# процент пропусков
print(round(len(df.loc[df['temperature_of_extremities'].isna()]) / len(df.index) * 100, 1), "%")

18.7 %

In [68]:
#заменим пропуски на самое частое значение
df['temperature_of_extremities'].fillna(df.groupby(['age', 'surgery'])['temperature_of_extremities'].transform('max'), inplace = True)
df['temperature_of_extremities']

0      3.0
1      4.0
2      1.0
3      4.0
4      4.0
      ...
295    4.0
296    3.0
297    4.0
298    3.0
299    4.0
Name: temperature_of_extremities, Length: 300, dtype: float64

In [69]:
# заменим на категорийное значение
df.loc[df['temperature_of_extremities'] == 1, 'temperature_of_extremities'] = 'Normal'
df.loc[df['temperature_of_extremities'] == 2, 'temperature_of_extremities'] = 'Warm'
df.loc[df['temperature_of_extremities'] == 3, 'temperature_of_extremities'] = 'Cool'
df.loc[df['temperature_of_extremities'] == 4, 'temperature_of_extremities'] = 'Cold'
df.head()

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,Cool,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,yes,adult,534817,39.2,88.0,20.0,Cold,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,no,adult,530334,38.3,40.0,24.0,Normal,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,yes,young,5290409,39.1,164.0,84.0,Cold,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,no,adult,530255,37.3,104.0,35.0,Cold,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2

In [70]:
#peripheral_pulse
# - subjective
# - possible values are:
#   1 = normal 
#   2 = increased 
#   3 = reduced 
#   4 = absent
#normal or increased p.p.are indicative of adequate circulation while reduced or absent indicate poor perfusion

# процент пропусков
print(round(len(df.loc[df['peripheral_pulse'].isna()]) / len(df.index) * 100, 1), "%")

23.0 %

In [71]:
#заменим пропуски на самое частое значение
df['peripheral_pulse'].fillna(df.groupby(['age', 'surgery'])['peripheral_pulse'].transform('max'), inplace = True)
df['peripheral_pulse']

0      3.0
1      4.0
2      1.0
3      1.0
4      4.0
      ...
295    4.0
296    2.0
297    3.0
298    3.0
299    4.0
Name: peripheral_pulse, Length: 300, dtype: float64

In [72]:
# заменим на категорийное значение
df.loc[df['peripheral_pulse'] == 1, 'peripheral_pulse'] = 'normal'
df.loc[df['peripheral_pulse'] == 2, 'peripheral_pulse'] = 'increased'
df.loc[df['peripheral_pulse'] == 3, 'peripheral_pulse'] = 'reduced'
df.loc[df['peripheral_pulse'] == 4, 'peripheral_pulse'] = 'absent'

df.head()

,surgery,age,hospital_number,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time,...,packed_cell_volume,total_protein,abdominocentesis_appearance,abdomcentesis_total_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,Cool,reduced,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,yes,adult,534817,39.2,88.0,20.0,Cold,absent,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,no,adult,530334,38.3,40.0,24.0,Normal,normal,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,yes,young,5290409,39.1,164.0,84.0,Cold,normal,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,no,adult,530255,37.3,104.0,35.0,Cold,absent,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2

In [73]:
# по результату обработки первых 8ми столбцов, пропуски отсутствуют
for col in df.columns:
    res = df[col].isnull().mean()
    print(f'{col} - {res : 0.1%}')

surgery -  0.0%
age -  0.0%
hospital_number -  0.0%
rectal_temperature -  0.0%
pulse -  0.0%
respiratory_rate -  0.0%
temperature_of_extremities -  0.0%
peripheral_pulse -  0.0%
mucous_membranes -  15.7%
capillary_refill_time -  10.7%
pain -  18.3%
peristalsis -  14.7%
abdominal_distension -  18.7%
nasogastric_tube -  34.7%
nasogastric_reflux -  35.3%
nasogastric_reflux_PH -  82.3%
rectal_examination_feces -  34.0%
abdomen -  39.3%
packed_cell_volume -  9.7%
total_protein -  11.0%
abdominocentesis_appearance -  55.0%
abdomcentesis_total_protein -  66.0%
outcome -  0.3%
surgical_lesion -  0.0%
lesion_1 -  0.0%
lesion_2 -  0.0%
lesion_3 -  0.0%
cp_data -  0.0%